version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - ./webpack.config.js:/app/webpack.config.js
    environment:
      - NODE_ENV=development
    command: npm run dev && npm run webpack
  auth-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./src/authServer.ts:/app/src/authServer.ts
      - ./tsconfig.json:/app/tsconfig.json
    environment:
      - NODE_ENV=development
    command: npm run devAuth