version: "3"
services:
  node-app:
    build: 
      context: .
      dockerfile: Dockerfile_web
    ports:
      - "8030:8030"
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
      - auth-app
  auth-app:
    build: 
      context: .
      dockerfile: Dockerfile_auth
    ports:
      - "8020:8020"
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
  postgres:
    build: 
      context: .
      dockerfile: Dockerfile_db
    ports: 
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=D@c77357
      - POSTGRES_DB=wikibuilder